version: '3.8'

services:
  frontend:
    image: fr0ste/ecomm-front:latest
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-https://ec2-18-118-129-110.us-east-2.compute.amazonaws.com/}
    ports:
      - '3001:3000'
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
    networks:
      - app-network
    environment:
      - BACKEND_HOST=ec2-18-118-129-110.us-east-2.compute.amazonaws.com
      - BACKEND_PORT=443

networks:
  app-network:
    driver: bridge 